name: Movies.API

on:
  workflow_dispatch:
  push:
    branches:
      - main
    
    paths:
      - "Common/Auth/**"
      - "Services/Movies/Movies.Common/**"
      - "Services/Movies/Movies.API/**"
      - "Services/Screening/Screening.GRPC/Protos/screening.proto"
      - ".github/workflows/Movies.API.yml"

  pull_request:
    branches:
      - main
    
    paths:
      - "Common/Auth/**"
      - "Services/Movies/Movies.Common/**"
      - "Services/Movies/Movies.API/**"
      - "Services/Screening/Screening.GRPC/Protos/screening.proto"
      - ".github/workflows/Movies.API.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the Movie.API service
        shell: bash
        run: |
          cd Services/Movies/Movies.API
          dotnet build
